#!/bin/bash

mkdir -p ~/proj/website/pa/
cp -av icon* index.html luxon.js script.js sw.js styles.css \
   pa.webmanifest ~/proj/website/pa/

echo "Files copied to ~/proj/website -- you still need to deploy them!"
